### ISSUE TITLE
Error en el assert

### ISSUE THREAD

**Issue by Uriei** [PyED2018/Proyecto#1]
¿No debería ser 
```	assertEquals(usuario2.getRol(), Usuario.ROLES[1]);```
en lugar de
```	assertEquals(usuario1.getRol(), Usuario.ROLES[1]);``` 
?

https://github.com/PyED2018/Proyecto/blob/0934ac93bc71f8eff6cd34dc3c56a2639ee49ca2/JV2018/src/test/UsuarioTest.java#L115

**Comment by MiguelFerPi** [comment]
Y parece ser estos tambien se pasaron por alto y reemplazan datos en `usuario1` que provocan un error en el test de `testToString`:

https://github.com/PyED2018/Proyecto/blob/master/JV2018/src/test/UsuarioTest.java#L186-L191
y
https://github.com/PyED2018/Proyecto/blob/master/JV2018/src/test/UsuarioTest.java#L204-L207
